### PR TITLE
Develop josh

### PR DESCRIPTION
**Pull request by CSJosh**
Edit card functionality and layout is in the works. It currently should be set up to just pass the UN-EDITED video back to 'createACard' by responding to the intent passed to it. Of course this functionality is just a placeholder until backend is working and hooked up, and until the time-cropping works.

### CODE REVIEW

**Review by TsebMagi — CHANGES_REQUESTED** [review]
Can't instantiate a new external listener

**Comment by CSJosh** [comment]
Strange...must have pulled from another repo too because I didn't modify that file. looks to be from 'sharing' functionality

**Comment by TsebMagi** [comment]
you can comment it out and leave a note about it

**Comment by CSJosh** [comment]
I just commented out that block. Still fiddling...

**Review by TsebMagi — APPROVED** [review]

**Pull request merged**
